### ISSUE TITLE
How to make a VS code extension

### ISSUE THREAD

**Issue by byubean** [beanlab/vs-code-ai-extension#1]
figure it out
document

**Comment by EianWright** [comment]
This problem seems to have two parts to me. The first part is the interaction with VS code. The second part is setting up the API calls to the AIs. There's a few things that I've thought about to consider in regards to these parts.

### VS Code
- With the hope of allowing other AIs than just GPT in the future, we should create a setting that allows the user to choose which AI modal they are using. I think that this will be easier to implement from the start rather than as an after thought. Documentation for settings can be found [here](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration).
- Along the same line of thought, we will want to have a setting so that the user can input their own API key. We will want to add a check that an API key has been inputted whenever the user starts up VS code and log a warn as well as show a message notifying the user.
- I've had several thoughts on how we could handle the ui, but haven't really come to any conclusive "this way is the best". We could have our commands so they are runnable with ⌘⇧P or with a right click. We could make them runnable via a keyboard shortcut. We could have a window on the left of VS code (like the source control or remote explorer windows) to interact with the AI. We could use something like a git diff to show the suggested changes being made. I think that we should pick the one easiest way for now and get that working so that we can have a proof of concept as soon as possible.

### Set up API calls
- I've always used [axios](https://axios-http.com/docs/intro) for making API calls in JavaScript/TypeScript and think that we should use that. It should completely meet our needs.
- I think that we should have an abstract parent class that defines all the methods that our frontend will need (for example, completeCode, checkForBugs, cleanUpCode, etc). That way, we can inherit from that class and implement those methods differently based on the API. This should make extending the extension to use other AIs fairly easy without breaking things.
- We will want to have very robust error handling on these calls. If the server is down, we don't want our extension to crash. But we also want to be as helpful to the user as possible. If their API key is wrong and the server is returning a message/code indicating that, we should show a message to the user.
- We won't even want to call anything if the API key has not been inputted.
